### ISSUE TITLE
Please add support for new edge browser based on chromium 

### ISSUE THREAD

**Issue by bryanchapman9999** [LorenzoPane/browserdefault#30] opened 2020-01-29 19:19 UTC
Can get it to open by using device ID of com.microsoft.msedge but it needs a custom url scheme

**Comment by LorenzoPane** [comment] 2020-01-29 22:57
Try `microsoft-edge-https://` as documented [here](https://stackoverflow.com/questions/51025950/is-there-a-url-scheme-to-open-a-website-in-microsoft-edge-on-ios).

**Comment by bryanchapman9999** [comment] 2020-01-30 09:42
I did try that.
That opens edge, but then opens over 100 tabs for me

**Comment by LorenzoPane** [comment] 2020-01-30 22:47
I'll take a look sometime. I haven't been actively developing this tweak for some time and plan on rewriting it once my life settles down. Until then, Duplicate of #24

**Closed by LorenzoPane** 2020-01-30 22:47 UTC
