### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by Hemzax** [LorenzoPane/browserdefault#13] opened 2019-05-20 10:05 UTC
Hello, I’ve tried opening a link in YouTube using Chrome as my default browser in the tweak as well as in the YouTube app, but it doesn’t seem to redirect me to a link, it only opens Chrome.

**Comment by LemonJuiz** [comment] 2019-05-20 11:07
Same here. Confirmed it was BrowserDefault because when it is switched back to Safari links open in Chrome correctly. Must be an issue with YouTube trying to open Chrome on its own and the link gets lost in the handoff from BrowserDefault to Chrome.

**Comment by LorenzoPane** [comment] 2019-05-20 21:03
This can be temporarily fixed by setting your default browser *within the youtube app* to Safari.  If I find the time, I'll look into removing this conflict.

**Closed** 2019-05-21 00:26 UTC
