### ISSUE TITLE
Links not opening correctly in chrome

### ISSUE THREAD

**Issue by allendude51** [LorenzoPane/browserdefault#16] opened 2019-05-25 03:55 UTC
Every time I open a link using the Safari webview it adds another https when opening in chrome and thus it won't load the website. I've attached a photo of it happening when I tried opening a link from sileo
![32A52BC5-AB05-4C53-8448-37F19BD6C70F](https://user-images.githubusercontent.com/51012842/58364248-ee412c00-7e76-11e9-9d0b-4bb2da1a915e.png)
![EDD87031-F8AA-4034-AF74-F288E4B067B3](https://user-images.githubusercontent.com/51012842/58364249-ee412c00-7e76-11e9-8099-0d82b2df070f.png)

**Comment by LorenzoPane** [comment] 2019-05-25 14:06
Duplicate of #15.  I'm looking into it now.

**Closed by LorenzoPane** 2019-05-25 14:06 UTC
